ci: Fix fastlane bundle version mismatch (#2177)
The upload to Testflight via Fastlane failed with
error: The CFBundleVersion of an App Clip ('1') must match that of its containing parent app ('817').
This is fixed now by using increment_build_number instead of using set_info_plist_value.